version: '3.4'
services:
  mysql:
    image: mysql:5
    container_name: mysql
    ports: 
        - "3306:3306"
    hostname: mysql
    environment:
        - MYSQL_ROOT_PASSWORD=/run/secrets/mysql_secret
        - MYSQL_USER=root
        - MYSQL_DATABASE=process-engine
    volumes:
        - "./mysql/init:/docker-entrypoint-initdb.d"
    secrets:
        - mysql_secret

  camunda:
    #build: webrest
    image: xinhuagu/ms-camunda-demo_camunda:1.0 
    container_name: camunda
    ports: 
      - "8080:8080"
    hostname: camunda
    depends_on:
      - mysql
    links:
      - mysql:db
    environment:
      - DB_DRIVER=com.mysql.jdbc.Driver
      - DB_URL=jdbc:mysql://db:3306/process-engine?autoReconnect=true
      - DB_USERNAME=root
      - DB_PASSWORD=/run/secrets/mysql_secret
      - WAIT_FOR=db:3306
    secrets: 
      - mysql_secret
secrets:
    mysql_secret:
      file: "./mysql/mysql-pass.txt"
